--- 
title: "生物信息学实战手册"
author: "孟浩巍、大壮、官云小姐姐、刘博、连明、徐煜、契卡（按章节顺序排序）"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
bibliography:
- book.bib
- packages.bib
description: 生物信息学实战手册,从入门到独立承担课题
documentclass: ctexbook
geometry:
- b5paper
- tmargin=2.5cm
- bmargin=2.5cm
- lmargin=3.5cm
- rmargin=2.5cm
link-citations: yes
lof: yes
lot: yes
colorlinks: yes
site: bookdown::bookdown_site
biblio-style: apalike
---

```{r setup, include=FALSE}
options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 55, digits = 4
)

# 填上你需要用到的包，如 c('ggplot2', 'dplyr')
lapply(c(), function(pkg) {
  if (system.file(package = pkg) == '') install.packages(pkg)
})
```


# 前言 {-}

生物信息学的本质是使用信息学的手段解决生物学问题。自20世纪60年代发端以来，生物信息学对整个生物领域的发展产生了巨大的影响。2003年在多国科学家的通力合作下，科学家们完成了人类参考基因组的测序，随后越来越多模式生物的参考基因组也完成拼装，生物信息学或者说整个生物学的研究进入了一个新纪元。

2006年Illumina公司开发了第二代测序技术（Next Generation Sequencing，NGS），随着NGS技术的推广，一系列之前看似天方夜谭的测序技术得到应用：

- 如可以对人的每一个基因进行表达水平测定的RNA-Seq技术；
- 对基因组每一个突变进行鉴定的全基因组测序（Whole Genome Sequencing，WGS）；
- 对表观遗传学甲基化水平进行刻画的BS-Seq；
- 对基因组三维结构进行详细刻画的Hi-C技术，ChIA-PET技术等等。

也是因为这些技术的推广与应用，目前生物信息学一个很大的挑战就是理解和分析这些海量的数据。

在分析数据的过程中，使用R语言或者Python语言对原始的生物信息数据进行清洗，加工，分析，展示已经成为主流。不但使用便捷，而且两种编程语言都是开源语言没有版权和商业的限制，更重要的是使用人数众多，常见的问题都能过通过Google搜索到解决方案。

但是在生物信息学蓬勃发展的今天，国内鲜有一本能够将编程技术与实际生物信息学分析结合起来的参考书目，这给众多想要入门生物信息学的同学，老师及需要数据分析的临床医生带来了非常大的挑战。入门门槛较高，学习曲线比较陡峭是妨碍大家学习生信的主要问题，因此本书尝试用贴近真实数据分析的视角，为大家讲解我们认为最重要的生信相关知识点，并给出完整的测试数据及代码，方便大家进行学习。

我们不期能够大而全地介绍每一个生物信息学细节，而希望为大家提供一份较为通俗易懂的入门实战手册，在阅读和实践的过程中逐渐感受到生物信息学数据的处理方式，领会数据处理的原理。同时，针对生物信息学中涉及到的R语言，统计学及相关生物背景知识我也会给出相应的学习建议，方便大家更加深入地学习。



## 致谢 {-}

非常感谢我们编写团队的共同努力，没有各位的付出是不可能有这本书的存在。

在成书过程中：

- 孟浩巍主要负责第1、2、7、8章内容；
- 大壮主要负责第3章的内容；
- 官云小姐姐主要负责第4章的内容；
- 刘博主要负责了第5章的内容；
- 徐煜负责了第8章tSNE部分的内容；
- 契卡主要负责了第9章的内容；

另外，也要非常感谢生物信息学交流群里的朋友和每一位关心、支持我们的朋友，谢谢你们！

```{block2, type='flushright', html.tag='p'}
生物信息学实战手册编写团队
```
